spring:
  db1:
    datasource:
      jdbc-url: jdbc:log4jdbc:mysql://sql-cloudgame-dev-mysql.mysql.database.azure.com:3306/txdb_2nd?serverTimezone=UTC&characterEncoding=UTF8&autoReconnect=true&useSSL=true
      #username: xclouddevadmin@sql-cloudgame-dev-mysql
      #password: 'Xclouddev2020#07'
      username: xclouddevadmin@sql-cloudgame-dev-mysql
      password: Xclouddev2020#07
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      poolName: hkr
      idleTimeout: 100000
      minimumIdle: 10
      maximumPoolSize: 10
      connectionTimeout: 9000
      maxLifetime: 110000

mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  type-aliases-package:
    com.example/cp3
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 700000
    jdbc-type-for-null: NULL
    default-executor-type: REUSE
    cache-enabled: TRUE
    lazy-loading-enabled: TRUE