version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run:
          name: Build and Test
          command: ./gradlew clean build

  run-local:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run:
          name: Run Locally
          command: java -jar build/libs/demo-0.0.1-SNAPSHOT.jar